services:
  node:
    container_name: docker_node2
    build:
      context: ./
      target: node
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - .:/app
